[[mgr.prepend_keymap]]
on   = ["g", "s"]
run  = "cd ~/Nextcloud/Scanbox"
desc = "Go to Scanbox"

[[mgr.prepend_keymap]]
on   = ["g", "f"]
run  = 'shell --block -- ya emit cd "$(fd . -t d -t l --follow ~ 2>/dev/null | fzf)"'
desc = "Fuzzy jump to dir (incl. symlinks) under ~"
